
POST http://localhost:9090/users/register HTTP/1.1
content-type: application/json

{
    "name": "bahubali",
    "username": "bahu",
    "email": "b@b.com",
    "password": "password123"
}

###

POST http://localhost:9090/users/login HTTP/1.1
content-type: application/json

{
    "email": "b@b.com",
    "password": "password123"
}
