
POST http://localhost:9090/users/register HTTP/1.1
content-type: application/json

{
    "name": "bahubali",
    "username": "bahu",
    "email": "bb@gmail.com",
    "password": "1111"
}
###

POST http://localhost:9090/users/login HTTP/1.1
content-type: application/json

{
    "email": "bb@gmail.com",
    "password": "1111"
}

###
GET  http://localhost:9090/user/get_user_and_profile HTTP/1.1
content-type: application/json

{
    "token":"6dd3fa8ddffa727bd8c60a2ff0ca09f4e47ab8f466ec823c787d3b6485e3b96e"
}

###
POST http://localhost:9090/user/update_profile_data HTTP/1.1
content-type: application/json

{
    "token":"a3991b70cc06f8564ae14724dd30e4674e3268820652aef50e453dcdaf60fe81",
    "bio":"Bahubali",
    "currentPost":"Maharaja",
    "pastWork":[
        {
            "company":"Maheshmati samrajya",
        "position":"Raja",
        "fieldOfStudy":"Leadership"
        }
    ],
    "education":[
        {"school":"Maheshmati University",
        "degree":"12th fail",
        "fieldOfStudy":"Naaah."
        }
    ]
}
###
GET http://localhost:9090/user/user/get_All_Users HTTP/1.1
###
POST /create_post HTTP/1.1
Host: localhost:9090
Content-Type: application/json
Content-Length:  70

{"token":"a3991b70cc06f8564ae14724dd30e4674e3268820652aef50e453dcdaf60fe81"}

###
GET http://localhost:9090/posts HTTP/1.1

###
DELETE  http://localhost:9090/delete_post HTTP/1.1
content-type: application/json

{
    "token":"f53a037a32a16bfefc4ee7f66ae66f42739e359592b14473d03cfd8c100e9874",
    "postId":"685ce693f95a8d69dc14d608"
}