
POST http://localhost:9090/users/register HTTP/1.1
content-type: application/json

{
    "name": "bahubali",
    "username": "bahu",
    "email": "bb@gmail.com",
    "password": "1111"
}
###

POST http://localhost:9090/user/login HTTP/1.1
content-type: application/json

{
    "email": "vs@gmail.com",
    "password": "vs"
}

###
GET  http://localhost:9090/user/get_user_and_profile?token=6bc7c3f0a1e932e06e36eb94577bcdc48ad53239f4a5ea19281db30c77fe99dd HTTP/1.1
# content-type: application/json

# {
#     "token":""
# }

###
POST http://localhost:9090/user/update_profile_data HTTP/1.1
content-type: application/json

{
    "token":"46aa3dabd7ca61923903160f0d7739e0ed61972b88db88877a6a36ba1e6b35d8",
    "bio":"Hii I am sahil yuvraj kamble",
    "currentPost":"Maharaja",
    "pastWork":[
        {
            "company":"Maheshmati samrajya",
        "position":"Raja",
        "Year":"4"
        },
        {
            "company":"TATA Consultancy Services",
        "position":"Software Engineer",
        "Year":"2"
        }
    ],
    "education":[
        {"school":"Maheshmati University",
        "degree":"12th fail",
        "fieldOfStudy":"Naaah."
        }
    ]
}
###
GET http://localhost:9090/user/user/get_All_Users HTTP/1.1
###
POST /create_post HTTP/1.1
Host: localhost:9090
Content-Type: application/json
Content-Length:  70

{"token":"a3991b70cc06f8564ae14724dd30e4674e3268820652aef50e453dcdaf60fe81"}

###
GET http://localhost:9090/posts HTTP/1.1

###
DELETE  http://localhost:9090/delete_post HTTP/1.1
content-type: application/json

{
    "token":"f53a037a32a16bfefc4ee7f66ae66f42739e359592b14473d03cfd8c100e9874",
    "postId":"685ce693f95a8d69dc14d608"
}


###
GET http://localhost:9090/user/getProfileUsingUsername HTTP/1.1
content-type: application/json

{
    "username":"sk2448"
}